language: java
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/cargo-daemon

install: true

script:
  - mvn -U verify -Dwdm.gitHubTokenName=${WDM_GITHUB_USER} -Dwdm.gitHubTokenSecret=${WDM_GITHUB_TOKEN}
